FROM node:22.17.0-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9.15.0 --activate && apk add --no-cache wget
ENV PATH="/root/.corepack:$PATH"

COPY package.json pnpm-workspace.yaml .npmrc turbo.json pnpm-lock.yaml ./
COPY apps/api/package.json ./apps/api/
COPY packages/broker-contracts/package.json ./packages/broker-contracts/

RUN corepack pnpm install --frozen-lockfile

EXPOSE 3000

CMD ["sh", "-c", "corepack pnpm exec turbo run build --filter=./packages/* && corepack pnpm --filter @info-tec/api run dev:api"]
